### ISSUE TITLE
Because firestore_search >=0.1.0 depends on cloud_firestore ^0.14.0 and "My Application" depends on cloud_firestore ^0.16.0+1, firestore_search >=0.1.0 is forbidden.

### ISSUE THREAD

**Issue by kareemX** [asadamatic/firestore_search#4]

**Comment by mayank09** [comment]
I am also facing same issue:

Because firestore_search >=0.1.0 depends on cloud_firestore ^0.14.0 and MyApp depends on cloud_firestore ^2.2.1, firestore_search >=0.1.0 is forbidden.
So, because MyApp depends on firestore_search ^0.1.2, version solving failed.
pub get failed (1; So, because MyApp depends on firestore_search ^0.1.2, version solving failed.)

**Comment by asadamatic** [comment]
Okay, I'll publish a version for `cloud_firestore ^2.2.2`, I believe it should work for both.

**Comment by mayank09** [comment]
thanks buddy

**Comment by asadamatic** [comment]
You're welcome :)
The update is live now.

**Comment by mayank09** [comment]
Really appreciated your quick action buddy :)
